#!/usr/bin/env ruby

ENV_PATH  = File.expand_path('../../config/environment',  __FILE__)
BOOT_PATH = File.expand_path('../../config/boot',  __FILE__)
APP_PATH  = File.expand_path('../../config/application',  __FILE__)

require ENV_PATH
require 'delayed/command'

if RUBY_VERSION.to_f >= 1.9
  STDERR.puts "!!! delayed_job has only been successfully tested with Ruby 1.8.x !!!"
end

Delayed::Command.new(ARGV).daemonize
